import { LegalPage, legalMetadata } from "@/components/legal-page";

export const metadata = legalMetadata("Privacy", "How the Flint website and launcher handle information.");

export default function PrivacyPage() {
  return <LegalPage eyebrow="Privacy / Website + launcher" title="Privacy" intro="The website and the Flint launcher are different surfaces. This policy explains both without pretending that ordinary infrastructure produces no data." sections={[
    { title:"Website behavior", paragraphs:["This website is a mostly static product site. It does not include account registration, contact forms, advertising trackers, or first-party analytics in this version.","The site itself does not intentionally store personal information in browser local storage. If the site is hosted on Vercel or another provider, that provider may process routine request data such as IP address, user agent, requested path, timestamp, and diagnostic logs for security and delivery." ]},
    { title:"Cookies", paragraphs:["This version does not set non-essential cookies and therefore does not display a consent banner. The hosting platform may use strictly necessary security or delivery mechanisms; review the host’s policy for details." ]},
    { title:"Outbound links", paragraphs:["Links to GitHub, Discord, and X leave this website. Those services receive requests under their own terms and privacy policies. Flint does not control their collection or retention practices." ]},
    { title:"Launcher data", paragraphs:["Flint stores profiles, settings, selected worlds, managed-mod manifests, logs, and other launcher configuration locally under the Windows user account. Local/offline identities are not authenticated Microsoft sessions. People with access to that Windows account may be able to read this non-secret game data.","Discord Rich Presence is optional. When enabled, it receives basic launcher state and game version; Flint’s current security guidance says server addresses, usernames, and profile names are not sent." ]},
    { title:"AutoAuth and credentials", paragraphs:["AutoAuth is experimental and opt-in. Passwords are designed to be stored through the Windows-native keyring in Windows Credential Manager. Profile configuration contains a credential reference rather than the password. The feature is intended only for an exact configured offline-mode server after the player explicitly requests a login or registration command.","The launcher’s published security guidance says credentials should not be placed in profile JSON, logs, Discord activity, diagnostics, imports, exports, or URLs. AutoAuth should remain disabled on untrusted servers." ]},
    { title:"Retention and control", paragraphs:["Website infrastructure logs are retained according to the chosen hosting provider’s configuration. Launcher data stays on the user’s device until the user removes it, uninstalls data, or a particular feature documents another retention period. Removing an AutoAuth entry is intended to delete its Windows Credential Manager item." ]},
  ]} />;
}
